<?php

namespace UserBundle\Repository;

/**
 * UserInstrumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserInstrumentRepository extends \Doctrine\ORM\EntityRepository
{
}
